services:
  nextjs-mongo:
    image: mongo:latest
    container_name: nextjs-mongo
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=m11615
      - MONGO_INITDB_DATABASE=nextjs
    volumes:
      - nextjs-mongo-volume:/data/db
    networks:
      - nextjs-network
    restart: no

  nextjs-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: nextjs-server
    ports:
      - "4000:4000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nextjs-network
    depends_on:
      - nextjs-mongo
    restart: no

  nextjs-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: nextjs-client
    ports:
      - "4001:4001"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - nextjs-network
    extra_hosts:
      - "server:host-gateway"
    depends_on:
      - nextjs-server
    restart: no

volumes:
  nextjs-mongo-volume:
    driver: local

networks:
  nextjs-network:
    driver: bridge
